# Generated by Django 5.2.11 on 2026-02-25 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=64, unique=True)),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('fine_cap', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('hold_window_hours', models.PositiveIntegerField(default=48)),
                ('max_renewals', models.PositiveIntegerField(default=2)),
                ('default_loan_period_days', models.PositiveIntegerField(default=14)),
                ('default_max_active_loans', models.PositiveIntegerField(default=5)),
                ('fine_block_threshold', models.DecimalField(decimal_places=2, default=300, help_text='If member unpaid fines exceed this threshold, block checkout/renew.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(max_length=16)),
                ('book_type', models.CharField(max_length=16)),
                ('loan_period_days', models.PositiveIntegerField()),
                ('max_active_loans', models.PositiveIntegerField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_rules', to='policies.librarypolicy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('policy', 'member_type', 'book_type'), name='uniq_rule_per_policy_member_book')],
            },
        ),
    ]
