# Generated by Django 5.2.11 on 2026-03-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_create_default_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarypolicy',
            options={'verbose_name': 'Politikë biblioteke', 'verbose_name_plural': 'Politika biblioteke'},
        ),
        migrations.AlterModelOptions(
            name='loanrule',
            options={'verbose_name': 'Rregull huazimi', 'verbose_name_plural': 'Rregulla huazimi'},
        ),
        migrations.AddField(
            model_name='librarypolicy',
            name='reservation_grace_days',
            field=models.PositiveIntegerField(default=0, help_text='Days after pickup_date before approved reservation auto-expires.'),
        ),
        migrations.AddField(
            model_name='librarypolicy',
            name='reservation_warning_hours',
            field=models.PositiveIntegerField(default=24, help_text='Warning window before reservation auto-expiry (hours).'),
        ),
    ]
