# Generated by Django 5.2.11 on 2026-02-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Titulli')),
                ('excerpt', models.TextField(blank=True, default='', verbose_name='Përshkrim i shkurtër')),
                ('content', models.TextField(blank=True, default='', verbose_name='Përmbajtje')),
                ('published_at', models.DateTimeField(verbose_name='Publikuar më')),
                ('is_published', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.CharField(blank=True, default='Info', max_length=40, verbose_name='Etiketa')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='Shfaq në faqen kryesore')),
            ],
            options={
                'verbose_name': 'Njoftim',
                'verbose_name_plural': 'Njoftime',
                'ordering': ('-published_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Titulli')),
                ('excerpt', models.TextField(blank=True, default='', verbose_name='Përshkrim i shkurtër')),
                ('content', models.TextField(blank=True, default='', verbose_name='Përmbajtje')),
                ('published_at', models.DateTimeField(verbose_name='Publikuar më')),
                ('is_published', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, default='', max_length=180, verbose_name='Vendndodhja')),
                ('badge', models.CharField(blank=True, default='Event', max_length=40, verbose_name='Etiketa')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Fillon më')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Mbaron më')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Evente',
                'ordering': ('-published_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Titulli')),
                ('excerpt', models.TextField(blank=True, default='', verbose_name='Përshkrim i shkurtër')),
                ('content', models.TextField(blank=True, default='', verbose_name='Përmbajtje')),
                ('published_at', models.DateTimeField(verbose_name='Publikuar më')),
                ('is_published', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_url', models.URLField(verbose_name='Linku i videos')),
                ('badge', models.CharField(blank=True, default='Video', max_length=40, verbose_name='Etiketa')),
                ('duration', models.CharField(blank=True, default='', max_length=32, verbose_name='Kohëzgjatja')),
                ('show_on_home', models.BooleanField(default=False, verbose_name='Shfaq në faqen kryesore')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video',
                'ordering': ('-published_at', '-id'),
            },
        ),
    ]
