# Generated by Django 5.2.11 on 2026-02-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/announcements/', verbose_name='Foto (opsionale)'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/events/', verbose_name='Foto (opsionale)'),
        ),
    ]
