# Generated by Django 5.2.11 on 2026-03-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_announcement_image_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Emri')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=160, verbose_name='Subjekti')),
                ('message', models.TextField(verbose_name='Mesazhi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dërguar më')),
                ('is_read', models.BooleanField(default=False, verbose_name='E lexuar')),
            ],
            options={
                'verbose_name': 'Mesazh',
                'verbose_name_plural': 'Mesazhet',
                'ordering': ('-created_at',),
            },
        ),
    ]
