# Generated by Django 5.2.11 on 2026-03-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_add_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/videos/', verbose_name='Foto (opsionale)'),
        ),
    ]
