# Generated by Django 5.2.11 on 2026-03-18 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_video_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='U përgjigj'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Përgjigjur më'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='Përgjigjur nga'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_body',
            field=models.TextField(blank=True, default='', verbose_name='Përgjigja'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_subject',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='Subjekti i përgjigjes'),
        ),
    ]
