# Generated by Django 5.2.11 on 2026-02-26 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'verbose_name': 'Profil anëtari', 'verbose_name_plural': 'Profile anëtarësh'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Përdorues', 'verbose_name_plural': 'Përdorues'},
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktiv'), ('SUSPENDED', 'Pezulluar'), ('BLOCKED', 'I bllokuar')], default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('STAFF', 'Staf/Librarian'), ('MEMBER', 'Anëtar')], default='MEMBER', max_length=16),
        ),
    ]
