# Generated by Django 5.2.11 on 2026-02-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_memberprofile_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Datëlindja'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Nr. ID'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='place_of_birth',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Vendlindja'),
        ),
    ]
