# Generated by Django 5.2.11 on 2026-02-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_memberprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='member_no',
            field=models.CharField(blank=True, default='', max_length=32, unique=True),
        ),
    ]
