# Generated by Django 5.2.11 on 2026-07-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_terms_acceptance_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='memberprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id', ''), _negated=True), fields=('national_id',), name='accounts_memberprofile_national_id_unique_when_set'),
        ),
    ]
