# Generated by Django 5.2.11 on 2026-03-01 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circulation', '0006_loan_loaned_by_loan_returned_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=64, verbose_name='Veprimi')),
                ('severity', models.CharField(choices=[('INFO', 'Informative'), ('INCIDENT', 'Incident')], default='INFO', max_length=16, verbose_name='Niveli')),
                ('app_label', models.CharField(max_length=64, verbose_name='Aplikacioni')),
                ('model_name', models.CharField(max_length=64, verbose_name='Modeli')),
                ('object_id', models.CharField(max_length=64, verbose_name='ID objekti')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='Objekti')),
                ('source_screen', models.CharField(blank=True, default='', max_length=128, verbose_name='Ekrani burim')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Arsye')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Ndryshimet')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Krijuar më')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Përdoruesi')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='circulation.loan', verbose_name='Huazimi')),
            ],
            options={
                'verbose_name': 'Auditim',
                'verbose_name_plural': 'Auditime',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='audit_audit_created_81b39b_idx'), models.Index(fields=['app_label', 'model_name', 'object_id'], name='audit_audit_app_lab_e82e9a_idx'), models.Index(fields=['action_type', 'severity'], name='audit_audit_action__a8c59c_idx'), models.Index(fields=['loan', 'created_at'], name='audit_audit_loan_id_58410d_idx')],
            },
        ),
    ]
