# Generated by Django 5.2.11 on 2026-03-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='auditentry',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='User-Agent / Browser'),
        ),
    ]
