# Generated by Django 5.2.11 on 2026-02-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autorë'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Libër', 'verbose_name_plural': 'Libra'},
        ),
        migrations.AlterModelOptions(
            name='copy',
            options={'verbose_name': 'Kopje', 'verbose_name_plural': 'Kopje'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Zhanër', 'verbose_name_plural': 'Zhanre'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Botues', 'verbose_name_plural': 'Botues'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiketë', 'verbose_name_plural': 'Etiketa'},
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('GENERAL', 'I përgjithshëm'), ('REFERENCE', 'Referencë (vetëm në bibliotekë)')], default='GENERAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='copy',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'E mirë'), ('FAIR', 'Mesatare'), ('POOR', 'E dobët')], default='GOOD', max_length=12),
        ),
        migrations.AlterField(
            model_name='copy',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponueshme'), ('ON_LOAN', 'Në huazim'), ('ON_HOLD', 'Në pritje për marrje'), ('LOST', 'Humbur'), ('DAMAGED', 'Dëmtuar'), ('IN_PROCESSING', 'Në përpunim')], default='AVAILABLE', max_length=20),
        ),
    ]
