# Generated by Django 5.2.11 on 2026-02-25 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('READY_FOR_PICKUP', 'Ready for pickup'), ('EXPIRED', 'Expired'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='catalog.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='accounts.memberprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['book', 'status', 'position'], name='circulation_book_id_ba62fa_idx'), models.Index(fields=['member', 'status'], name='circulation_member__25cce8_idx')],
                'constraints': [models.UniqueConstraint(fields=('book', 'position'), name='uniq_hold_position_per_book')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned')], default='ACTIVE', max_length=16)),
                ('loaned_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('renew_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='catalog.copy')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='accounts.memberprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'due_at'], name='circulation_status_389498_idx')],
            },
        ),
    ]
