# Generated by Django 5.2.11 on 2026-02-27 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_memberprofile_date_of_birth_and_more'),
        ('catalog', '0002_alter_author_options_alter_book_options_and_more'),
        ('circulation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hold',
            options={'verbose_name': 'Rezervim', 'verbose_name_plural': 'Rezervime'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Huazim', 'verbose_name_plural': 'Huazime'},
        ),
        migrations.AlterField(
            model_name='hold',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Në radhë'), ('READY_FOR_PICKUP', 'Gati për marrje'), ('EXPIRED', 'Skaduar'), ('FULFILLED', 'U realizua'), ('CANCELLED', 'Anuluar')], default='WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktiv'), ('RETURNED', 'I kthyer')], default='ACTIVE', max_length=16),
        ),
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Në pritje'), ('APPROVED', 'Pranuar'), ('REJECTED', 'Refuzuar'), ('CANCELLED', 'Anuluar')], default='PENDING', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Shënim (opsionale)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Arsye (për refuzim)')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_requests', to='catalog.book')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_request_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Vendosur nga')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_requests', to='accounts.memberprofile')),
            ],
            options={
                'verbose_name': 'Kërkesë për rezervim',
                'verbose_name_plural': 'Kërkesa për rezervim',
                'indexes': [models.Index(fields=['status', 'created_at'], name='circulation_status_5f8ee0_idx'), models.Index(fields=['member', 'status', 'created_at'], name='circulation_member__5601bc_idx'), models.Index(fields=['book', 'status', 'created_at'], name='circulation_book_id_7a4bc8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('member', 'book'), name='uniq_pending_request_per_member_book')],
            },
        ),
    ]
