# Generated by Django 5.2.11 on 2026-02-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_alter_hold_options_alter_loan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationrequest',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Do ta marrë më'),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Do ta dorëzojë më'),
        ),
    ]
