# Generated by Django 5.2.11 on 2026-02-27 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_memberprofile_member_no'),
        ('catalog', '0002_alter_author_options_alter_book_options_and_more'),
        ('circulation', '0003_reservationrequest_pickup_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField(verbose_name='Do ta marrë më')),
                ('return_date', models.DateField(verbose_name='Do ta dorëzojë më')),
                ('status', models.CharField(choices=[('APPROVED', 'Rezervim i pranuar'), ('BORROWED', 'U huazua'), ('EXPIRED', 'Skaduar'), ('CANCELLED', 'Anuluar')], default='APPROVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.book')),
                ('loan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_reservation', to='circulation.loan', verbose_name='Huazimi')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='accounts.memberprofile')),
                ('source_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='circulation.reservationrequest', verbose_name='Kërkesa burimore')),
            ],
            options={
                'verbose_name': 'Rezervim',
                'verbose_name_plural': 'Rezervime',
                'indexes': [models.Index(fields=['status', 'pickup_date'], name='circulation_status_455234_idx'), models.Index(fields=['book', 'status', 'pickup_date'], name='circulation_book_id_1d4be1_idx'), models.Index(fields=['member', 'status', 'pickup_date'], name='circulation_member__525aa2_idx')],
            },
        ),
    ]
