# Generated by Django 5.2.11 on 2026-02-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Shënim'),
        ),
    ]
