# Generated by Django 5.2.11 on 2026-02-28 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_memberprofile_member_no'),
        ('catalog', '0002_alter_author_options_alter_book_options_and_more'),
        ('circulation', '0005_loan_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loaned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_loans', to=settings.AUTH_USER_MODEL, verbose_name='Huazuar nga (stafi)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL, verbose_name='Dorëzuar nga (stafi)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='borrowed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_from_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Huazuar nga (stafi)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Krijuar nga (stafi)'),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Regjistruar nga (stafi)'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='catalog.copy', verbose_name='Kopja'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_at',
            field=models.DateTimeField(verbose_name='Afati i kthimit'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loaned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Huazuar më'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='accounts.memberprofile', verbose_name='Anëtari'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='renew_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nr. zgjatjeve'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kthyer më'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktiv'), ('RETURNED', 'I kthyer')], default='ACTIVE', max_length=16, verbose_name='Statusi'),
        ),
    ]
