# Generated by Django 5.2.13 on 2026-04-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0006_loan_loaned_by_loan_returned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='due_soon_reminder_for',
            field=models.DateField(blank=True, help_text='Data e afatit të kthimit për të cilën është dërguar tashmë njoftimi një ditë para.', null=True, verbose_name='Kujtesë “afati nesër” dërguar për'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_soon_reminder_for',
            field=models.DateField(blank=True, help_text='Data e marrjes për të cilën është dërguar tashmë njoftimi një ditë para.', null=True, verbose_name='Kujtesë “marrje nesër” dërguar për'),
        ),
    ]
