"""
Django settings for smart_library project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="django-insecure-dev-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])
if DEBUG and "testserver" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("testserver")

# HTTPS në Render / proxy; CSRF për login admin
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# Render.com: variabla të vendosura automatikisht (pa nevojë për ALLOWED_HOSTS manual)
_render_url = os.environ.get("RENDER_EXTERNAL_URL", "").strip()
if _render_url:
    _pu = urlparse(_render_url)
    if _pu.netloc:
        ALLOWED_HOSTS = list(dict.fromkeys([*ALLOWED_HOSTS, _pu.netloc, ".onrender.com"]))
        _origin = f"{_pu.scheme}://{_pu.netloc}"
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS = list(CSRF_TRUSTED_ORIGINS) + [_origin]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Seancë: rinovohet në çdo kërkesë → skadon pas ~SESSION_COOKIE_AGE sekondash pa aktivitet (idle).
SESSION_COOKIE_AGE = env.int("SESSION_COOKIE_AGE", default=3600)
SESSION_SAVE_EVERY_REQUEST = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'drf_spectacular',

    # Local apps
    'accounts',
    'catalog',
    'circulation',
    'fines',
    'policies',
    'audit',
    'cms',
    'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'cms.middleware.AdminAccessGuardMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smart_library.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notification_bell',
            ],
        },
    },
]

WSGI_APPLICATION = 'smart_library.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = env("DATABASE_URL", default="").strip()
if DATABASE_URL:
    DATABASES = {"default": env.db_url("DATABASE_URL")}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'sq'

TIME_ZONE = 'Europe/Tirane'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("sq", "Shqip"),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
# Në VPS: vendos MEDIA_ROOT jashtë repo-s (p.sh. /var/lib/biblioteka/media) që të mos
# humbasin ngarkimet pas git pull / git clean; nginx duhet të shërbejë të njëjtin path.
_media_root_env = env("MEDIA_ROOT", default="").strip()
MEDIA_ROOT = Path(_media_root_env) if _media_root_env else BASE_DIR / "media"

if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Smart Library API",
    "DESCRIPTION": "MVP API for catalog, circulation, fines, and policies.",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

ACCESS_TOKEN_LIFETIME_MINUTES = env.int("ACCESS_TOKEN_LIFETIME_MINUTES", default=60)
REFRESH_TOKEN_LIFETIME_DAYS = env.int("REFRESH_TOKEN_LIFETIME_DAYS", default=7)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": __import__("datetime").timedelta(
        minutes=ACCESS_TOKEN_LIFETIME_MINUTES
    ),
    "REFRESH_TOKEN_LIFETIME": __import__("datetime").timedelta(
        days=REFRESH_TOKEN_LIFETIME_DAYS
    ),
}

EMAIL_FROM_ADDRESS = env("EMAIL_FROM_ADDRESS", default="").strip()
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="").strip()
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="").strip()
OPS_REPORT_RECIPIENTS = [e.strip() for e in env.list("OPS_REPORT_RECIPIENTS", default=[]) if e.strip()]
OPS_ALERT_OVERDUE_LOANS_THRESHOLD = env.int("OPS_ALERT_OVERDUE_LOANS_THRESHOLD", default=10)
OPS_ALERT_OVERDUE_RESERVATIONS_THRESHOLD = env.int("OPS_ALERT_OVERDUE_RESERVATIONS_THRESHOLD", default=5)
OPS_ALERT_PENDING_REQUESTS_THRESHOLD = env.int("OPS_ALERT_PENDING_REQUESTS_THRESHOLD", default=20)
OPS_ALERT_UNPAID_FINES_TOTAL_THRESHOLD = env("OPS_ALERT_UNPAID_FINES_TOTAL_THRESHOLD", default="1000.00").strip()
NOTIFY_DUE_SOON_DAYS = env.int("NOTIFY_DUE_SOON_DAYS", default=2)
NOTIFY_FINE_CREATED_LOOKBACK_DAYS = env.int("NOTIFY_FINE_CREATED_LOOKBACK_DAYS", default=3)
NOTIFY_RESERVATION_EXPIRY_HOURS = env.int("NOTIFY_RESERVATION_EXPIRY_HOURS", default=24)
SMS_WEBHOOK_URL = env("SMS_WEBHOOK_URL", default="").strip()
SMS_WEBHOOK_TOKEN = env("SMS_WEBHOOK_TOKEN", default="").strip()
PUBLIC_BASE_URL = env("PUBLIC_BASE_URL", default="").strip()

# Use SMTP if configured; fallback to console for local dev.
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
    EMAIL_PORT = env.int("EMAIL_PORT", default=587)
    EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
    EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
    DEFAULT_FROM_EMAIL = EMAIL_FROM_ADDRESS or EMAIL_HOST_USER
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = EMAIL_FROM_ADDRESS or "no-reply@localhost"
LOGIN_URL = "/hyr/"

JAZZMIN_SETTINGS = {
    "site_title": "Smart Library",
    "site_header": "Smart Library",
    "site_brand": "Smart Library",
    "site_logo": "img/logo_biblioteka.png",
    "site_icon": "img/logo_biblioteka.png",
    "login_logo": "img/logo_biblioteka.png",
    "site_logo_classes": "brand-image",
    "welcome_sign": "Mirësevini në panelin e bibliotekës",
    "copyright": "Smart Library",
    "custom_js": "jazzmin/js/topbar_user.js",
    # Keep navbar clean (Jazzmin renders one search box per model).
    "search_model": ["catalog.Copy", "accounts.MemberProfile"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": [
        "circulation",
        "circulation.loan",
        "circulation.reservationrequest",
        "circulation.reservation",
        "accounts",
        "catalog",
        "cms",
        "cms.contactmessage",
        "cms.announcement",
        "cms.event",
        "cms.weeklybook",
        "notifications",
        "notifications.usernotification",
        "fines",
        "policies",
    ],
    "icons": {
        "accounts.user": "fas fa-user-shield",
        "accounts.memberprofile": "fas fa-id-card",
        "catalog.book": "fas fa-book",
        "catalog.copy": "fas fa-barcode",
        "catalog.author": "fas fa-pen-nib",
        "catalog.genre": "fas fa-tags",
        "catalog.publisher": "fas fa-building",
        "catalog.tag": "fas fa-hashtag",
        "circulation.reservationrequest": "fas fa-inbox",
        "circulation.loan": "fas fa-exchange-alt",
        "circulation.reservation": "fas fa-calendar-check",
        "cms.contactmessage": "fas fa-envelope",
        "cms.announcement": "fas fa-bullhorn",
        "cms.event": "fas fa-calendar-alt",
        "cms.weeklybook": "fas fa-book-open",
        "cms.video": "fas fa-video",
        "fines.fine": "fas fa-receipt",
        "fines.payment": "fas fa-cash-register",
        "policies.librarypolicy": "fas fa-sliders-h",
        "policies.loanrule": "fas fa-list-ol",
    },
    "hide_models": [
        "circulation.hold",
        "catalog.publisher",
        "catalog.tag",
        "catalog.copy",
        "catalog.genre",
        "catalog.author",
        "policies.librarypolicy",
        "policies.loanrule",
        "cms.video",
    ],
    "topmenu_links": [
        {"name": "Faqja", "url": "/", "new_window": True},
    ],
    "custom_css": "css/admin.css",
    "language_chooser": False,
    "changeform_format": "horizontal_tabs",
}

# Jazzmin UI Tweaks (teal/jeshile si SMIP)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-teal",
    "navbar": "navbar-dark navbar-teal",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-teal",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "minty",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-success",
    },
}
