# Generated by Django 5.2.13 on 2026-04-20 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reservation_new_staff', 'Kërkesë e re (staf)'), ('reservation_cancelled_staff', 'Kërkesë e anuluar (staf)'), ('reservation_submitted_member', 'Kërkesa u dërgua'), ('reservation_approved_member', 'Rezervim i pranuar'), ('reservation_rejected_member', 'Kërkesa u refuzua'), ('hold_ready_member', 'Gati për marrje'), ('loan_active_member', 'Huazim aktiv'), ('loan_returned_member', 'Libri u kthye'), ('loan_renewed_member', 'Afati u zgjat'), ('reservation_expired_member', 'Rezervimi skadoi')], db_index=True, max_length=64)),
                ('title', models.CharField(max_length=220)),
                ('body', models.TextField(blank=True, default='')),
                ('link_url', models.CharField(blank=True, default='', max_length=500)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Njoftim përdoruesi',
                'verbose_name_plural': 'Njoftime përdoruesish',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_776dd3_idx'), models.Index(fields=['user', 'read_at'], name='notificatio_user_id_05d802_idx')],
            },
        ),
    ]
